#!/usr/bin/env node
/*
 * Copyright (C) 2026 ezTxmMC
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of Lumen IDE. It is free software: you can redistribute it
 * and/or modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version. See the LICENSE file for details.
 */

/**
 * Compiles the H2 bridge (`src/drivers/h2/Bridge.java`) and embeds the class
 * file in `src/drivers/h2/bridge-class.js`. Shipping the compiled class means
 * users only need a Java runtime, not a JDK.
 *
 *   node extensions/database/scripts/build-bridge.mjs
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.join(HERE, '..', 'src', 'drivers', 'h2');

const out = await fs.mkdtemp(path.join(os.tmpdir(), 'lumen-h2-bridge-'));
try {
  const result = spawnSync('javac', ['--release', '11', '-d', out, path.join(DIR, 'Bridge.java')], { stdio: 'inherit' });
  if (result.status !== 0) {
    throw new Error('javac failed');
  }
  const classes = (await fs.readdir(out)).filter((name) => name.endsWith('.class'));
  if (classes.length !== 1 || classes[0] !== 'Bridge.class') {
    throw new Error(`Expected only Bridge.class, got: ${classes.join(', ')}`);
  }
  const base64 = (await fs.readFile(path.join(out, 'Bridge.class'))).toString('base64');
  const source = [
    '// Generated by scripts/build-bridge.mjs from Bridge.java — do not edit.',
    '// The compiled H2 bridge (Java 11 bytecode), written to disk on first use.',
    `export const BRIDGE_CLASS = '${base64}'`,
    '',
  ].join('\n');
  await fs.writeFile(path.join(DIR, 'bridge-class.js'), source, 'utf8');
  process.stdout.write(`✓ bridge-class.js (${base64.length} chars)\n`);
} finally {
  await fs.rm(out, { recursive: true, force: true });
}
